excerpt_separator: ""
pygments: true
markdown: kramdown
title: AJI
tagline: my document
description: My awesome new site via <a href="https://tinypress.co/" target="_blank">Tinypress</a>
paginate: 1